repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        exclude: route53/mastering-route53.yaml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.59.0 # The version of cfn-lint to use
    hooks:
    -   id: cfn-python-lint
        files: route53/.*\.(json|yml|yaml)$
        exclude: route53/parameters.enc.json
